services:
    server_start_command:
        class: phoopy.http.http_bundle.source.command.ServerStartCommand
        kwargs:
            logger: '@logger'
            container: '@container'
            flask_config: '@flask.config'
            phoopy_http_config: '@phoopy_http.config'
        tag:
            - command
